import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Image from "next/image.js";
import Button from "@/components/Button/index.js";
import Account from "@/components/Account/index.js";
import Facebook from "@/components/Facebook/index.js";
import App from "@/components/App/index.js";
import Form from "@/components/Form";
import Or from "@/components/Or";
import Forgot from "@/components/Forgot";
import Footer from "@/components/Footer/index.js";

export default function Home() {
	return (
		<>
			<Head>
				<title>Instagram Login Page</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={`${styles.main}`}>
				<div className={`${styles.pageContainer}`}>
					<div className={`${styles.loginContainer}`}>
						<div className={`${styles.wordmark}`}>
							<Image
								src={"/images/instagram-wordmark.png"}
								alt="instagram wordmark"
								width={250}
								height={90}
								priority
							/>
						</div>
						<Form />
						<Button />
						<Or />
						<Facebook />
						<Forgot />
					</div>
					<Account />
					<App />
				</div>
			</main>
			<div className={styles.footerPlacement}>
				<Footer />
			</div>
		</>
	);
}
